In [1]:
import random
import numpy as np
import time
import numba
import math
from numpy.random import Generator, PCG64DXSM, SeedSequence
import multiprocessing as mp
from structure2_BIG_FNs_00 import play_sequence

np.set_printoptions(suppress=True)

In [2]:
# use this cell for setting initial perameters

# rng = np.random.default_rng()

sides = 2
pairs = np.asarray([[0, 1], [1, 0], [1, 2], [2, 1], [2, 3], [3, 2], [3, 4], [4, 3]])
testpairs = np.asarray([[1, 3], [3, 1]])
nonadjpairs = np.asarray([[0, 2], [2, 0], [0, 3], [3, 0], [0, 4], [4, 0], [1, 4], [4, 1], [2, 4], [4, 2]])
allpairs = np.concatenate((pairs, nonadjpairs, testpairs))

plen = len(pairs)
alen = len(allpairs)

terms = 5
# maxvalue = 10
startstop = 2
# noise = 0.2
annealing = 0.000003

timesteps = 6*10**7
runs = 100

# rein1 = 4
# rein2 = 0
# punish1 = 0
# punish2 = -8
inertia = 1

nsteps = 100
# blocklength = nsteps*10


In [3]:
# use this cell for running the code

#measuring how long code takes to run
start = time.perf_counter()



#nprocs = mp.cpu_count()-1
pool = mp.Pool(processes=25)

sg = SeedSequence()
rgs = [Generator(PCG64DXSM(s)) for s in sg.spawn(runs)]


for blocklength in [1000, 10000]:
    for maxvalue in [5, 10, 15, 20]:
        for noise in [0., .2]:
            for rein1 in range(2, 9, 2):
                for rein2 in range(0, 9, 2):
                    for punish1 in range(0, -9, -2):
                        for punish2 in range(0, -21, -2):
                            
                            mpseq_final = pool.starmap(play_sequence, [(n, rgs[n], rein1, punish1, rein2, punish2, timesteps, nsteps, sides, pairs, testpairs, nonadjpairs, allpairs, plen, alen, terms, maxvalue, startstop, noise, annealing, runs, inertia, blocklength) for n in range(runs)])

                            final_sigweights = []
                            final_cumsuc = []
                            final_cumsucadd = []
                            final_testcumsucadd = []
                            final_recweights = []

                            for res_idx in range(0, len(mpseq_final)):

                                final_sigweights.append(mpseq_final[res_idx][0])
                                final_cumsuc.append(mpseq_final[res_idx][1])
                                final_cumsucadd.append(mpseq_final[res_idx][2])
                                final_testcumsucadd.append(mpseq_final[res_idx][3])
                                final_recweights.append(mpseq_final[res_idx][4])

                            final_sigweights = np.asarray(final_sigweights)
                            final_cumsuc = np.asarray(final_cumsuc)
                            final_cumsucadd = np.asarray(final_cumsucadd)
                            final_testcumsucadd = np.asarray(final_testcumsucadd)
                            final_recweights = np.asarray(final_recweights)
                            
                            
                            print("average final cumsucadd = ")
                            print(np.average(final_cumsucadd)/(100))
                            # print(" ")

                            print("average test cumsum = ")
                            print(np.average(final_testcumsucadd)/(100))
                        
                            print(f'rein1 = {rein1} rein2 = {rein2} punish1 = {punish1} punish2 = {punish2}')
                            print(f'blocklengh = {blocklength} maxvalue = {maxvalue} noise = {noise}')
                            
                            print(" ")
                            print(" ")

finish = time.perf_counter()
print(f'Finished in {round(finish-start,0)/60} minutes')

average final cumsucadd = 
0.6408
average test cumsum = 
0.5304
rein1 = 2 rein2 = 0 punish1 = 0 punish2 = 0
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7070000000000001
average test cumsum = 
0.7559999999999999
rein1 = 2 rein2 = 0 punish1 = 0 punish2 = -2
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7121999999999999
average test cumsum = 
0.7176
rein1 = 2 rein2 = 0 punish1 = 0 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6992
average test cumsum = 
0.6955
rein1 = 2 rein2 = 0 punish1 = 0 punish2 = -6
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6831
average test cumsum = 
0.6790999999999999
rein1 = 2 rein2 = 0 punish1 = 0 punish2 = -8
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6674
average test cumsum = 
0.6629
rein1 = 2 rein2 = 0 punish1 = 0 punish2 = -10
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cu

average final cumsucadd = 
0.5777
average test cumsum = 
0.7258
rein1 = 2 rein2 = 0 punish1 = -8 punish2 = -14
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.5807
average test cumsum = 
0.7354
rein1 = 2 rein2 = 0 punish1 = -8 punish2 = -16
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.5863
average test cumsum = 
0.7415
rein1 = 2 rein2 = 0 punish1 = -8 punish2 = -18
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.5767
average test cumsum = 
0.7387
rein1 = 2 rein2 = 0 punish1 = -8 punish2 = -20
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6437
average test cumsum = 
0.5275
rein1 = 2 rein2 = 2 punish1 = 0 punish2 = 0
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6714
average test cumsum = 
0.6063000000000001
rein1 = 2 rein2 = 2 punish1 = 0 punish2 = -2
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7195999999999999

average final cumsucadd = 
0.7091
average test cumsum = 
0.7928000000000001
rein1 = 2 rein2 = 2 punish1 = -8 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6840999999999999
average test cumsum = 
0.7761
rein1 = 2 rein2 = 2 punish1 = -8 punish2 = -6
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6575
average test cumsum = 
0.7794
rein1 = 2 rein2 = 2 punish1 = -8 punish2 = -8
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.633
average test cumsum = 
0.7489
rein1 = 2 rein2 = 2 punish1 = -8 punish2 = -10
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.626
average test cumsum = 
0.7555
rein1 = 2 rein2 = 2 punish1 = -8 punish2 = -12
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6126
average test cumsum = 
0.7495
rein1 = 2 rein2 = 2 punish1 = -8 punish2 = -14
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6088

average final cumsucadd = 
0.6613
average test cumsum = 
0.7831999999999999
rein1 = 2 rein2 = 4 punish1 = -6 punish2 = -18
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6587000000000001
average test cumsum = 
0.7733
rein1 = 2 rein2 = 4 punish1 = -6 punish2 = -20
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7240000000000001
average test cumsum = 
0.7714
rein1 = 2 rein2 = 4 punish1 = -8 punish2 = 0
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7336
average test cumsum = 
0.7829
rein1 = 2 rein2 = 4 punish1 = -8 punish2 = -2
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7381
average test cumsum = 
0.821
rein1 = 2 rein2 = 4 punish1 = -8 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7326
average test cumsum = 
0.8129000000000001
rein1 = 2 rein2 = 4 punish1 = -8 punish2 = -6
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average fi

average final cumsucadd = 
0.7273999999999999
average test cumsum = 
0.7998999999999999
rein1 = 2 rein2 = 6 punish1 = -6 punish2 = -8
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7217
average test cumsum = 
0.8147
rein1 = 2 rein2 = 6 punish1 = -6 punish2 = -10
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7115
average test cumsum = 
0.772
rein1 = 2 rein2 = 6 punish1 = -6 punish2 = -12
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7111
average test cumsum = 
0.7970999999999999
rein1 = 2 rein2 = 6 punish1 = -6 punish2 = -14
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6986
average test cumsum = 
0.8027
rein1 = 2 rein2 = 6 punish1 = -6 punish2 = -16
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.69
average test cumsum = 
0.7974
rein1 = 2 rein2 = 6 punish1 = -6 punish2 = -18
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsuc

average final cumsucadd = 
0.7217
average test cumsum = 
0.8217
rein1 = 2 rein2 = 8 punish1 = -4 punish2 = -20
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6551
average test cumsum = 
0.5866
rein1 = 2 rein2 = 8 punish1 = -6 punish2 = 0
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6746
average test cumsum = 
0.5885
rein1 = 2 rein2 = 8 punish1 = -6 punish2 = -2
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7014
average test cumsum = 
0.7
rein1 = 2 rein2 = 8 punish1 = -6 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.718
average test cumsum = 
0.7042
rein1 = 2 rein2 = 8 punish1 = -6 punish2 = -6
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7228
average test cumsum = 
0.7777
rein1 = 2 rein2 = 8 punish1 = -6 punish2 = -8
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7304999999999999
average test cum

average final cumsucadd = 
0.7045999999999999
average test cumsum = 
0.8504999999999999
rein1 = 4 rein2 = 0 punish1 = -4 punish2 = -10
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6845
average test cumsum = 
0.835
rein1 = 4 rein2 = 0 punish1 = -4 punish2 = -12
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6748000000000001
average test cumsum = 
0.8267
rein1 = 4 rein2 = 0 punish1 = -4 punish2 = -14
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6597
average test cumsum = 
0.8259000000000001
rein1 = 4 rein2 = 0 punish1 = -4 punish2 = -16
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6474
average test cumsum = 
0.8205
rein1 = 4 rein2 = 0 punish1 = -4 punish2 = -18
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6355
average test cumsum = 
0.8037000000000001
rein1 = 4 rein2 = 0 punish1 = -4 punish2 = -20
blocklengh = 1000 maxvalue = 5 noise = 0

average final cumsucadd = 
0.6846
average test cumsum = 
0.5887
rein1 = 4 rein2 = 2 punish1 = -4 punish2 = 0
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7148
average test cumsum = 
0.6329
rein1 = 4 rein2 = 2 punish1 = -4 punish2 = -2
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7240000000000001
average test cumsum = 
0.747
rein1 = 4 rein2 = 2 punish1 = -4 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7297
average test cumsum = 
0.7931
rein1 = 4 rein2 = 2 punish1 = -4 punish2 = -6
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7272
average test cumsum = 
0.7978000000000001
rein1 = 4 rein2 = 2 punish1 = -4 punish2 = -8
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7145999999999999
average test cumsum = 
0.8343
rein1 = 4 rein2 = 2 punish1 = -4 punish2 = -10
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd

average final cumsucadd = 
0.736
average test cumsum = 
0.7797
rein1 = 4 rein2 = 4 punish1 = -2 punish2 = -12
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7337
average test cumsum = 
0.7894
rein1 = 4 rein2 = 4 punish1 = -2 punish2 = -14
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7284
average test cumsum = 
0.8031999999999999
rein1 = 4 rein2 = 4 punish1 = -2 punish2 = -16
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7295
average test cumsum = 
0.7928000000000001
rein1 = 4 rein2 = 4 punish1 = -2 punish2 = -18
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7253000000000001
average test cumsum = 
0.8112999999999999
rein1 = 4 rein2 = 4 punish1 = -2 punish2 = -20
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6681999999999999
average test cumsum = 
0.5668
rein1 = 4 rein2 = 4 punish1 = -4 punish2 = 0
blocklengh = 1000 maxvalue = 5 noise = 0.0

average final cumsucadd = 
0.6803
average test cumsum = 
0.563
rein1 = 4 rein2 = 6 punish1 = -2 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6879000000000001
average test cumsum = 
0.5784
rein1 = 4 rein2 = 6 punish1 = -2 punish2 = -6
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7216
average test cumsum = 
0.6773
rein1 = 4 rein2 = 6 punish1 = -2 punish2 = -8
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7304999999999999
average test cumsum = 
0.7234
rein1 = 4 rein2 = 6 punish1 = -2 punish2 = -10
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7375
average test cumsum = 
0.7633
rein1 = 4 rein2 = 6 punish1 = -2 punish2 = -12
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7454999999999999
average test cumsum = 
0.764
rein1 = 4 rein2 = 6 punish1 = -2 punish2 = -14
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsuca

average final cumsucadd = 
0.7456
average test cumsum = 
0.772
rein1 = 4 rein2 = 8 punish1 = 0 punish2 = -16
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7398
average test cumsum = 
0.7648999999999999
rein1 = 4 rein2 = 8 punish1 = 0 punish2 = -18
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7273000000000001
average test cumsum = 
0.7681
rein1 = 4 rein2 = 8 punish1 = 0 punish2 = -20
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6375
average test cumsum = 
0.5186
rein1 = 4 rein2 = 8 punish1 = -2 punish2 = 0
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6507
average test cumsum = 
0.532
rein1 = 4 rein2 = 8 punish1 = -2 punish2 = -2
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.667
average test cumsum = 
0.5437
rein1 = 4 rein2 = 8 punish1 = -2 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.684800000

average final cumsucadd = 
0.7134999999999999
average test cumsum = 
0.7770999999999999
rein1 = 6 rein2 = 0 punish1 = 0 punish2 = -8
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7044
average test cumsum = 
0.7413
rein1 = 6 rein2 = 0 punish1 = 0 punish2 = -10
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7047
average test cumsum = 
0.7501000000000001
rein1 = 6 rein2 = 0 punish1 = 0 punish2 = -12
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6978
average test cumsum = 
0.7175
rein1 = 6 rein2 = 0 punish1 = 0 punish2 = -14
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6898000000000001
average test cumsum = 
0.7036
rein1 = 6 rein2 = 0 punish1 = 0 punish2 = -16
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.679
average test cumsum = 
0.6890000000000001
rein1 = 6 rein2 = 0 punish1 = 0 punish2 = -18
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 


average final cumsucadd = 
0.6994
average test cumsum = 
0.8592
rein1 = 6 rein2 = 0 punish1 = -8 punish2 = -20
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6381
average test cumsum = 
0.5322
rein1 = 6 rein2 = 2 punish1 = 0 punish2 = 0
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6368
average test cumsum = 
0.5432
rein1 = 6 rein2 = 2 punish1 = 0 punish2 = -2
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6668000000000001
average test cumsum = 
0.5832999999999999
rein1 = 6 rein2 = 2 punish1 = 0 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6883
average test cumsum = 
0.6397999999999999
rein1 = 6 rein2 = 2 punish1 = 0 punish2 = -6
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7084
average test cumsum = 
0.6908
rein1 = 6 rein2 = 2 punish1 = 0 punish2 = -8
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 


average final cumsucadd = 
0.7352
average test cumsum = 
0.8390000000000001
rein1 = 6 rein2 = 2 punish1 = -8 punish2 = -10
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7291
average test cumsum = 
0.8518000000000001
rein1 = 6 rein2 = 2 punish1 = -8 punish2 = -12
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7247
average test cumsum = 
0.8541
rein1 = 6 rein2 = 2 punish1 = -8 punish2 = -14
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7240000000000001
average test cumsum = 
0.8568000000000001
rein1 = 6 rein2 = 2 punish1 = -8 punish2 = -16
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7181000000000001
average test cumsum = 
0.8539
rein1 = 6 rein2 = 2 punish1 = -8 punish2 = -18
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7161
average test cumsum = 
0.8604999999999999
rein1 = 6 rein2 = 2 punish1 = -8 punish2 = -20
blocklengh = 1000 maxvalue 

average final cumsucadd = 
0.7170000000000001
average test cumsum = 
0.637
rein1 = 6 rein2 = 4 punish1 = -8 punish2 = -2
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7281
average test cumsum = 
0.7222
rein1 = 6 rein2 = 4 punish1 = -8 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7334
average test cumsum = 
0.7505
rein1 = 6 rein2 = 4 punish1 = -8 punish2 = -6
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7434000000000001
average test cumsum = 
0.7713
rein1 = 6 rein2 = 4 punish1 = -8 punish2 = -8
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7392
average test cumsum = 
0.8016
rein1 = 6 rein2 = 4 punish1 = -8 punish2 = -10
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.74
average test cumsum = 
0.8305
rein1 = 6 rein2 = 4 punish1 = -8 punish2 = -12
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.731800

average final cumsucadd = 
0.7423000000000001
average test cumsum = 
0.8306999999999999
rein1 = 6 rein2 = 6 punish1 = -6 punish2 = -16
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7328
average test cumsum = 
0.8044
rein1 = 6 rein2 = 6 punish1 = -6 punish2 = -18
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7354
average test cumsum = 
0.8209000000000001
rein1 = 6 rein2 = 6 punish1 = -6 punish2 = -20
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6844
average test cumsum = 
0.5590999999999999
rein1 = 6 rein2 = 6 punish1 = -8 punish2 = 0
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.6957
average test cumsum = 
0.5947
rein1 = 6 rein2 = 6 punish1 = -8 punish2 = -2
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average final cumsucadd = 
0.7182
average test cumsum = 
0.642
rein1 = 6 rein2 = 6 punish1 = -8 punish2 = -4
blocklengh = 1000 maxvalue = 5 noise = 0.0
 
 
average f

Process ForkPoolWorker-13:
Process ForkPoolWorker-6:
Process ForkPoolWorker-9:
Process ForkPoolWorker-3:
Process ForkPoolWorker-23:
Process ForkPoolWorker-7:
Process ForkPoolWorker-24:
Process ForkPoolWorker-21:
Process ForkPoolWorker-15:
Process ForkPoolWorker-5:
Process ForkPoolWorker-11:
Process ForkPoolWorker-8:
Process ForkPoolWorker-14:
Process ForkPoolWorker-4:
Process ForkPoolWorker-17:
Process ForkPoolWorker-12:
Process ForkPoolWorker-22:
Process ForkPoolWorker-1:
Process ForkPoolWorker-10:
Process ForkPoolWorker-2:
Process ForkPoolWorker-18:
Process ForkPoolWorker-25:
Process ForkPoolWorker-19:
Process ForkPoolWorker-20:
Traceback (most recent call last):
Process ForkPoolWorker-16:


KeyboardInterrupt: 

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/p

AttributeError: 'int' object has no attribute 'prod'
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kw

  File "/home/nothin/python/structure2/structure2_BIG_FNs_00.py", line 237, in play_sequence
    naturestates, randunif2, randunif4, randunif6, randunif8, naturesides = randoms(rng, nsteps, maxvalue, plen, alen, sides)
  File "/home/nothin/miniconda3/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
KeyboardInterrupt
  File "/home/nothin/python/structure2/structure2_BIG_FNs_00.py", line 237, in play_sequence
    naturestates, randunif2, randunif4, randunif6, randunif8, naturesides = randoms(rng, nsteps, maxvalue, plen, alen, sides)
  File "/home/nothin/python/structure2/structure2_BIG_FNs_00.py", line 238, in play_sequence
    recweights, sigweights, cumsucadd = nstepsfn(noise, plen, alen, maxvalue, naturesides, recweights, sigweights, randunif2, randunif4, randunif6, randunif8, naturestates, nsteps, allpairs, rein, punish)
  File "/home/nothin/python/structure2/structure2_BIG_FNs_00.py", line 238, in play_sequence
    

  File "/home/nothin/python/structure2/structure2_BIG_FNs_00.py", line 170, in randoms
    fnaturestates1 = frng.integers(fplen1*falen1, size=fnsteps1)
KeyboardInterrupt
KeyboardInterrupt
  File "_generator.pyx", line 540, in numpy.random._generator.Generator.integers
  File "/home/nothin/miniconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 69, in _wrapreduction
    def _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs):
  File "_bounded_integers.pyx", line 1228, in numpy.random._bounded_integers._rand_int64
KeyboardInterrupt
  File "<__array_function__ internals>", line 5, in prod
  File "/home/nothin/miniconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3051, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/home/nothin/miniconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 76, in _wrapreduction
    except AttributeError:
KeyboardInterrupt


In [4]:

# np.save('structure_noiseAnn_dsktp_BIG_2s_sigweights_c2', final_sigweights)
# np.save('structure_noiseAnn_dsktp_BIG_2s_recweights_c2', final_recweights)



In [6]:
idxy = 2
sigweights = final_sigweights[idxy]
cumsucadd = final_cumsucadd[idxy]
testcumsucadd = final_testcumsucadd[idxy]
recweights = final_recweights[idxy]

print(cumsucadd)
print(testcumsucadd)

87.0
75.0


In [8]:

simple_sig = np.zeros_like(sigweights)
for ax0 in range(0, sides):
    for ax1 in range(0, 2):
        for ax2 in range(0, terms):
            simplesum = sigweights[ax0, ax1, ax2][0]+sigweights[ax0, ax1, ax2][1]
            simple_sig[ax0, ax1, ax2][0] = math.floor(maxvalue*(sigweights[ax0, ax1, ax2][0] / simplesum))
            simple_sig[ax0, ax1, ax2][1] = math.floor(maxvalue*(sigweights[ax0, ax1, ax2][1] / simplesum))
            

print(simple_sig)
print(sigweights)

for s in range(0, sides):
    for l in range(0, terms):
        for s2 in range(0, sides):
            for r in range(0, terms):
                if l != r:
                    print(f'LEFT side: {s} term: {l} magnitude: {simple_sig[s, 0, l, 1]}')
                    print(f'RIGHT side: {s2} term: {r} magnitude: {simple_sig[s2, 1, r, 1]}')
                    print(f'receiver: {recweights[math.floor(simple_sig[s, 0, l, 1]*(maxvalue+1) + simple_sig[s2, 1, r, 1])]}')

[[[[14.  0.]
   [ 8.  6.]
   [ 0. 14.]
   [ 0. 14.]
   [12.  2.]]

  [[ 4. 10.]
   [ 6.  8.]
   [ 7.  7.]
   [ 0. 14.]
   [ 0. 14.]]]


 [[[14.  0.]
   [ 7.  7.]
   [ 0. 14.]
   [ 0. 14.]
   [10.  4.]]

  [[ 5.  9.]
   [ 6.  8.]
   [ 7.  7.]
   [ 0. 14.]
   [ 0. 14.]]]]
[[[[1.10386245e+08 1.57000000e+02]
   [1.04100000e+03 7.01000000e+02]
   [2.36762900e+06 2.22964593e+08]
   [2.93013300e+06 2.31217229e+08]
   [5.75310530e+07 1.03713690e+07]]

  [[7.70000000e+01 1.65000000e+02]
   [8.85465690e+07 1.14411833e+08]
   [2.28217610e+07 2.34657210e+07]
   [7.33836500e+06 1.22417337e+08]
   [7.68747300e+06 1.20172709e+08]]]


 [[[1.60832105e+08 1.00000000e+00]
   [2.81000000e+02 2.61000000e+02]
   [1.97664100e+06 1.86964081e+08]
   [1.76934900e+06 1.88444933e+08]
   [2.57000000e+02 1.05000000e+02]]

  [[1.41000000e+02 2.21000000e+02]
   [6.61931290e+07 8.28842530e+07]
   [2.06726970e+07 2.10618650e+07]
   [8.43535300e+06 1.34437249e+08]
   [9.02287300e+06 1.38524029e+08]]]]
LEFT side: 0 term: